### PR TITLE
Update to idasdk90

### PR DESCRIPTION
**Pull request by illnyang**

### CODE REVIEW

**Review by nvapi — APPROVED** [review]
I've also pushed this update on a forked repo, I think its better to seperate this so older versions (possibly also work?)

**Comment by illnyang** [comment]
Maybe something like `#if IDAVER >= 90 #else ` ?

**Comment by nvapi** [comment]
Would work I assume

**Comment by gir489returns** [comment]
Ill's doesn't compile because it says LNK1181	cannot open input file 'ida.lib'

nvapi's compiles and works. Should probably use his.

**Comment by nvapi** [comment]
> Ill's doesn't compile because it says LNK1181 cannot open input file 'ida.lib'
> 
> nvapi's compiles and works. Should probably use his.

Actual code logic is identical (since it's only updated ida sdk). You have to add ida.lib to the library path in vs, make sure linker also has ida.lib set

**Comment by A200K** [comment]
You are quite fast :)

Since the official IDA Version is still on 8.4 and 9.x plugins are likely not backwards compatible, I‘d like to keep the SDK versions separated (or at least in a separate branch) until v9.0 is officially released.
I also need to get my hands on IDA 9 first, I can take a look at it in a few weeks

**Comment by gir489returns** [comment]
240925 can't load this. 

```
LoadLibrary(C:\Users\Admin\AppData\Roaming\Hex-Rays\IDA Pro\plugins\SigMaker64.dll) error: The specified module could not be found.
C:\Users\Admin\AppData\Roaming\Hex-Rays\IDA Pro\plugins\SigMaker64.dll: can't load file
```

**Comment by nvapi** [comment]
> 240925 can't load this.
> 
> ```
> LoadLibrary(C:\Users\Admin\AppData\Roaming\Hex-Rays\IDA Pro\plugins\SigMaker64.dll) error: The specified module could not be found.
> C:\Users\Admin\AppData\Roaming\Hex-Rays\IDA Pro\plugins\SigMaker64.dll: can't load file
> ```

I mean it's lowkey telling you that the file does not exist. If it does just drag & drop the plugins folder into your IDA Installation instead of the appdata one aka `C:\Program Files\IDA Professional 9.0\plugins`

**Comment by gir489returns** [comment]
> > 240925 can't load this.
> > ```
> > LoadLibrary(C:\Users\Admin\AppData\Roaming\Hex-Rays\IDA Pro\plugins\SigMaker64.dll) error: The specified module could not be found.
> > C:\Users\Admin\AppData\Roaming\Hex-Rays\IDA Pro\plugins\SigMaker64.dll: can't load file
> > ```
> 
> I mean it's lowkey telling you that the file does not exist. If it does just drag & drop the plugin into your root ida plugins folder instead of the appdata one aka `C:\Program Files\IDA Professional 9.0\plugins`

Are you retarded? It's complaining that ida64.dll doesn't exist anymore, because it's ida.dll now. The SDK needs to be updated. "lowkey" fucking zoomers.

**Comment by nvapi** [comment]
> > > 240925 can't load this.
> > > ```
> > > LoadLibrary(C:\Users\Admin\AppData\Roaming\Hex-Rays\IDA Pro\plugins\SigMaker64.dll) error: The specified module could not be found.
> > > C:\Users\Admin\AppData\Roaming\Hex-Rays\IDA Pro\plugins\SigMaker64.dll: can't load file
> > > ```
> > 
> > 
> > I mean it's lowkey telling you that the file does not exist. If it does just drag & drop the plugin into your root ida plugins folder instead of the appdata one aka `C:\Program Files\IDA Professional 9.0\plugins`
> 
> Are you retarded? It's complaining that ida64.dll doesn't exist anymore, because it's ida.dll now. The SDK needs to be updated. "lowkey" fucking zoomers.

Ok relax for a second, no need to get hostile. Can you please point me where it says "ida64.dll" does not exist? And you do know right there is still both dlls even in 9.0... Plus zoomers? I think I am older than you

**Comment by gir489returns** [comment]
image

**Comment by gir489returns** [comment]
image

**Comment by nvapi** [comment]
> image

image

9.0 comes with ida64.dll and ida.dll,

**Comment by gir489returns** [comment]
No it does not.

**Comment by nvapi** [comment]
> No it does not.

Okay look, it does. I am the one who is correct at the current moment. I have no idea where you found your ida 9.0 leak but that is not the actual installation. Plus nobody else has this issue except you. First one to bring this up. I can send you my ida installer since i've downloaded the entire archive from actual hex-rays when it was up

**Comment by gir489returns** [comment]
> > No it does not.
> 
> Okay look, it does

Then why does your screenshot say the binary is from 8/10 and not 10/1? Learn how to read.

**Comment by nvapi** [comment]
> > > No it does not.
> > 
> > 
> > Okay look, it does
> 
> Then why does your screenshot say the binary is from 8/10 and not 10/1? Learn how to read. You installed IDA Pro RC1 into the same folder as the beta like a retard.

Dude you are actually beefing on a github pull? Also you are wrong again, and again and again. Look at my folder

image

The dates are different cause I had to patch the files, so ida can be used. CRACKED. Educate yourself please

**Comment by Ashesh3** [comment]
@nvapi @gir489returns 

On my fresh installation of IDA 9.0 RC1 I did not find a `ida64.dll`. This seems to be supported by the release notes: https://docs.hex-rays.com/release-notes/9_0#no-more-ida32 which states that only a single binary is handling both. Instead now I have `ida32.dll` and `ida.dll`.

I complied this plugin with the latest 9.0 RC1 SDK and it seems to be loading and working just fine without the `ida64.dll` being present.

Here's the complied DLL for anyone else wandering around: 
[SigMaker9_64.zip](https://github.com/user-attachments/files/17458230/SigMaker9_64.zip)

Just extract to your plugin folder.

If anyone wants to compile it for themselves, use the [IDA9](https://github.com/A200K/IDA-Pro-SigMaker/tree/IDA9) branch.

**Comment by gir489returnsagain** [comment]
@nvapi Cope and seethe at my victory (again).

**Comment by nvapi** [comment]
> @nvapi Cope and seethe at my victory (again).

Genuinely are you good? You dead seriously cannot let go of this. Plus you are still in the wrong but that's fine.

Installer (idapro_90_x64win.exe) with hash:
SHA256          4058FB9BDB56658B82ED2B4D1D5BAFD45FBFD4CECB671D7CB4087352BF6F2155

Contains both DLLs, go move on with life man

**Comment by gir489returnsagain** [comment]
> > @nvapi Cope and seethe at my victory (again).
> 
> Genuinely are you good? You dead seriously cannot let go of this. Plus you are still in the wrong but that's fine.

You are wrong. https://docs.hex-rays.com/release-notes/9_0#no-more-ida32

"We deprecated IDA32 a few versions ago. With IDA 9.0, just one IDA binary handles both 32- and 64-bit code."

Cope and seethe, I win you lose.

**Comment by nvapi** [comment]
> > > @nvapi Cope and seethe at my victory (again).
> > 
> > 
> > Genuinely are you good? You dead seriously cannot let go of this. Plus you are still in the wrong but that's fine.
> 
> You are wrong. https://docs.hex-rays.com/release-notes/9_0#no-more-ida32
> 
> "We deprecated IDA32 a few versions ago. With IDA 9.0, just one IDA binary handles both 32- and 64-bit code."
> 
> Cope and seethe, I win you lose.

Please read my message again, the installer I have listed above with the HASH. Has BOTH files. Oh and I see you have a new github. I wonder why

**Comment by gir489returnsagain** [comment]
> Please read my message again, the installer I have listed above with the HASH. 

You are wrong, get over it, I win you lose.

**Comment by nvapi** [comment]
> > Please read my message again, the installer I have listed above with the HASH.
> 
> You are wrong, get over it, I win you lose.

I mean you kinda give me free attention, I appreciate that. I am quite the loner man. Also you are wrong ❤️ Show me a video of you installing ida with this installer and opening the folder for proof. But I guess you cannot do that..

**Comment by gir489returnsagain** [comment]
> I mean you kinda give me free attention, I appreciate that. 
You can have all the attention as the loser you are, because you lost and I won, cope seethe and dilate.

**Comment by nvapi** [comment]
> > I mean you kinda give me free attention, I appreciate that.
> 
> You can have all the attention as the loser you are, because you lost and I won, cope seethe and dilate.

Yeah sure, whatever floats your boat dude. Like I said you have no evidence of the file hash I've listed not having both dlls. You list an official ida release, this is for the *leaked* version. e.g. beta90_6ba923

**Comment by gir489returnsagain** [comment]
> > > I mean you kinda give me free attention, I appreciate that.
> > 
> > 
> > You can have all the attention as the loser you are, because you lost and I won, cope seethe and dilate.
> 
> Yeah sure, whatever floats your boat dude. 

I win you lost, get over it.

**Pull request merged**
